# Generated by Django 3.2.7 on 2022-01-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=1, verbose_name='Event Date'),
        ),
    ]
