# Generated by Django 3.2.7 on 2022-01-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.IntegerField(blank=True, max_length=25, verbose_name='Contact Phone'),
        ),
    ]
